# Folders:
parent_path_images = "pictures"

untouched_scans_path = "1_untouched_input"
rough_cut_path = "2_rough_cut"
fine_cut_path = "3_output"


# Splitter
min_pixel_ratio = 0.05    # Minimum ratio of height/width of the scanned image that any contour must reach. Else the contour will be omitted.
detection_threshold = 190 # Note that this parameter refers to THRESH_BINARY_INV. Can be set between 0 and 255. https://docs.opencv.org/master/d7/d4d/tutorial_py_thresholding.html


# Finecut
detection_threshold_finecut = 200 # Threshold value: Higher values represent less aggressive contour search. If it's chosen too high, a white border will be introduced.
extra_crop = 10                   # Extra crop: After crop/rotate often a small white border remains. This removes this. If it cuts off too much of your image, adjust this.
