

parent_path_images = "pictures/"

[folders]
untouched_scans_path = "1_untouched"  # TODO This could be an argument.
rough_cut_path = "2_rough_cut"
error_rough_cut_path = "x_error_rough_cut"  # Files from this folder need to be manually cut.
fine_cut_path = "3_output"